### ISSUE TITLE
BUG: unable to access session / member in fetchExclude/IncludeRules

### ISSUE THREAD

**Issue by christopherdarling** [heyday/silverstripe-cacheinclude#28]
the `session` and `member` variables are a closure in `RequestCache::allowFetch()` (changed to this some time ago for perf reasons) and I can't find a valid way to use the expression language with the closure, for example using the below in either `fetchExcludeRules` or `fetchIncudeRules` config fails to run because `session` is an `Object` and not an `array`.

```
'SessionKey' in session
```

These may be better off as registered functions?

Update: works fine in 5.x - as not using closures anymore...

**Comment by stnvh** [comment]
Found a solution for this. Printed out the functions available for expression language when evaluting and found loads of methods apparently not documented anywhere. Settled on `key_exists("SessionKey", session)`.
