### ISSUE TITLE
unable to install on base SS3.7 install

### ISSUE THREAD

**Issue by vinstah** [heyday/silverstripe-cacheinclude#39]
Hello,
After installing SilverStripe 3.7 and trying to install this module (4.2) it fails on Symfony/yml.

This is because the version that SilverStripe/installer's PHPUnit requires is ^4 and this module has a requirement "symfony/yaml": "~2.4",

one work around is not to install the SilverStripe require-dev modules

**Comment by wilr** [comment]
Fixed in #41
