### ISSUE TITLE
Update symfony/yaml to allow for v4

### ISSUE THREAD

**Issue by obj63mc** [heyday/silverstripe-cacheinclude#40]
Currently Silverstripe is requiring symfony/yaml ^4.  When you try to install via 

    composer require heyday/silverstripe-cacheinclude:~5.0

With Silverstripe 4.7+ you get a conflict.  Can we bump to allow symfony/yaml ^3||^4

**Comment by ovogel-wigital** [comment]
SilverStripe requires symfony/yaml (^3.2 || ^4). So you can get away with this.

**Comment by HJGreen** [comment]
This has been fixed in [v5.1.0](https://github.com/heyday/silverstripe-cacheinclude/releases/tag/5.1.0) - thanks to @christopherdarling
